plugins:
  - jekyll-seo-tag

theme: jekyll-theme-minimal

google_analytics: UA-50551684-7

show_github_buttons: true


name: android-youtube-player
description: YouTube Player library for Android, stable and customizable.
author: Pierfrancesco Soffritti
author_email: soffritti.pierfrancesco@gmail.com

title: Android-YouTube-Player
url: https://pierfrancescosoffritti.github.io/android-youtube-player/
author: Pierfrancesco Soffritti
twitter:
  username: PierfrancescoSo

